# Generated by Django 5.2 on 2025-04-26 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height_cm', models.IntegerField()),
                ('current_weight_kg', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('physical_issues', models.TextField(blank=True, null=True)),
                ('has_gym_membership', models.BooleanField(default=False)),
                ('home_equipment', models.TextField(blank=True, null=True)),
                ('dietary_preferences', models.CharField(blank=True, max_length=100, null=True)),
                ('food_allergies', models.TextField(blank=True, null=True)),
                ('disliked_foods', models.TextField(blank=True, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], default='sedentary', max_length=50)),
                ('weight_loss_goal_kg', models.FloatField(blank=True, null=True)),
                ('desired_loss_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
